R2010a:
	mex -g -v -f ./mexopts.R2010a.sh -output vanilla_mexnc mexgateway.c netcdf4.c netcdf3.c netcdf2.c common.c 
	mv *.mex*  ../private

R2009b:
	mex -g -v -f ./mexopts.R2009b.sh -output vanilla_mexnc mexgateway.c netcdf4.c netcdf3.c netcdf2.c common.c 
	mv *.mex*  ../private

R2009a:
	mex -g -v -f ./mexopts.R2009a.sh -output vanilla_mexnc mexgateway.c netcdf4.c netcdf3.c netcdf2.c common.c 
	mv *.mex*  ../private

R2008b:
	mex -g -v -f ./mexopts.R2008b.sh -output vanilla_mexnc mexgateway.c netcdf4.c netcdf3.c netcdf2.c common.c 
	mv *.mex*  ../private

R2008a:
	mex -g -v -f ./mexopts.R2008a.sh -output vanilla_mexnc mexgateway.c netcdf4.c netcdf3.c netcdf2.c common.c 
	mv *.mex*  ../private

R2007b:
	mex -g -v -f ./mexopts.R2007b.sh -output vanilla_mexnc mexgateway.c netcdf2.c netcdf4.c netcdf3.c common.c 
	mv *.mex*  ../private

R2007a:
	mex -g -v -f ./mexopts.R2007a.sh -output vanilla_mexnc mexgateway.c netcdf2.c netcdf4.c netcdf3.c common.c 
	mv *.mex*  ../private

R2006b:
	mex -g -v -f ./mexopts.R2006b.sh -output vanilla_mexnc mexgateway.c netcdf2.c netcdf4.c netcdf3.c common.c 
	mv *.mex*  ../private

R2006a:
	mex -g -v -f ./mexopts.R2006a.sh -output vanilla_mexnc mexgateway.c netcdf2.c netcdf4.c netcdf3.c common.c 
	mv *.mex*  ../private

R14sp3:
	mex -g -v -f ./mexopts.R14sp3.sh -output vanilla_mexnc mexgateway.c netcdf2.c netcdf4.c netcdf3.c common.c 
	mv *.mex*  ../private


R13:
	mex -g -v -f ./mexopts.R13.sh -output vanilla_mexnc mexgateway.c netcdf2.c netcdf4.c netcdf3.c common.c 
	mv *.mex*  ../private


clean:
	rm -f *.o mexnc.mex*
